### PR TITLE
Add support for musical chord-workflows

### PR DESCRIPTION
**Pull request by MBauerDC**
This PR contains changes to the representation of chords, notes and note-steps to enable a music-theory focussed workflow. 

Immutable classes (with composition for note-steps) are used for these three structures in order to encapsulate default-values as static class constants and methods to compare notes/chords as well as generate new notes from existing notes and shifts by semitone and octave.

To enable configuration of chords, a `ChordConfiguration`-class has been added which enables explicit specification of chord-quality, suspension, extensions, additions, alterations, inversions, and omissions.

Since the logic of creating chords from a specification is quite complicated, the `GenericChord`-class is quite long, but everything has been factored into individual methods for handling the various parts.

Additionally, functions have been added to **parse chords** from chord-names and to **generate chord-names** for chords. Since the logic for each of these processes are again quite complicated, these functions are also rather long - but have been factored into sub-functions for parsing/writing the various parts.

No `let` has been used in the added/changed code - everything uses `const`, the ternary operator (not nested) and the null-coalescing operator.

The song-parts have been re-written using the changed/added code.

**Tests** have been added for all added/changed features - though the potential combinations of configuration-options for chords are exponentially vast, so writing tests for all possible combinations was not possible. In total, there are now 142 passing unit-tests.

### CODE REVIEW

**Comment by strangedev** [comment]
Hi @MBauerDC :wave: 
Thank you for the PR! I really like your idea a lot, especially parsing chords and having things like chord quality, inversions, additions and omissions. The only problem from my side is that I find it hard to fully understand what you have added and I don't know how I would use it. Your PR description contains a lot of technical detail about your work, but IMHO it doesn't describe the added features in enough detail to review them. If you could provide a list of changes with descriptions and maybe your reasoning why you added them, it would be a great help for reviewing this PR.

**Comment by strangedev** [comment]
One small nitpick: I think using special characters like `♭` could be hard to use, as many keyboard layouts don't provide these symbols. I believe the goal of this software is to be used by programmers, so maybe we can find some other representation that is more ASCII-compatible?

**Comment by MBauerDC** [comment]
Hi @strangedev :)

Oh, sorry - of course I'll gladly provide more commentary addressing those questions. Please do feel free to inquire about further details/explanation whenever questions arise.

As a quick note: the special characters are primarily used for writing Chord-names and deriving the correct note-names for those chords (e.g. Cdim7 is C-E♭-G♭-B𝄫, not c-d#-f#-a). 
For notes, the common designators (lowercase and with '#' only) can always be used. For chord-alterations and additions, 'b' and '#' can always be used instead of the musical UTF-8 symbols. 
Similarly, chord-qualities can always be written explicitly - e.g. 'dim' instead of '°' or 'halfDim' instead of 'ø'. 


## Added value
 * Specifying even very complex chords can now be done either by name (using `parseChord`) or by explicit configuration, instead of having to specify all the notes involved. This may offer preferred workflows for certain groups of users. Using `mapToNoteStep`, it is still possible to create note- and chord-patterns simple note-names.

 * Notes in chords now have the correct music-theoretical names (as mentioned above). This may be helpful for intelligibility to a wider musical audience / user base.

 * The added features of music-theoretically correct note-names, chord-configurations and chord-names facilitate the creation of a potential frontend with expressive namings for entities and flexible, expressive configuration-options.

 * To facilitate a simpler workflow, the `Chord`-interface enables getting an array of `NoteStep`s directly from the chord, with optional specification of velocity and duration either for all notes or even for individual notes. An optional custom constructor for `NoteStep`s from a `Note`, a `MidiValue` and a `Duration` can also be passed.


## Description of added/changed features

### Specific demnominators for `Duration`

Denominators for note-durations are specified in powers of two. The type has been changed to reflect that, allowing denominators from 2 to 128.


### Creating notes from other notes by semitone/octave shifts

Given an instance of `Note`, the method `getNoteFromInterval` enables passing a semitone-shift and an octave-shift to derive other notes. 
For some users, this may be a preferred workflow because they might think in terms of e.g. "I want the next note to be 7 semitones below this one" - in which case they need not 'translate' this thought into new note-names, and need not pay attention to enharmonic equivalence. It is also closer to the workflow on sequencers in a few prominent software-synths, where steps are specified by semitone-shifts from a starting note.

**Example**:
    
    const startNote = mapToNote('E_2');
    
    const _ = null;
    
    const patternNotes: (Note|null)[] = 
      [startNote, _, startNote.getNoteFromInterval(-7, 0), startNote.getNoteFromInterval(-1, 0),
       startNote, startNote.getNoteFromInterval(0,-1), _, _,
       startNote.getNoteFromInterval(-10, 0), _, _, startNote.getNoteFromInterval(-5, 0),
       _, _, startNote.getNoteFromInterval(-7, 0), _];
    
    const seqStepMapper: (note: Note|null) => Step = 
      (note: Note|null) => 
        (null === note) ? 
          createStep() : 
          createStep([mapToNoteStep(note)]);
    
    const pattern: Step[] = patternNotes.map(seqStepMapper);



### Creating chords from explicit configuration

Given a root-note, we can define notes explicitly using the concepts of chord-quality, extensions, suspension, inversions, additions, alterations and omissions. 
This offers the possibility for writing more musically expressive code, and for flexible configuration from a potential future (browser)-frontend.
It also enables re-use of chord-configurations across different root-notes. The workflow enabled by this change may also benefit users who frequently think in such terms.

**Example**

    const roots: NoteMappable[] = ['A3','C3','F2','G2'];
    const [A3, C3, F2, G2]: Note[] = roots.map(mapToNote);
    
    const chordConfigMin2ndInvDrop2: ChordConfiguration = {quality: 'min', inversion: 2, droppedPositions: [2]};
    const chordConfigMaj2ndInvDrop2: ChordConfiguration = {quality: 'Maj', inversion: 2, droppedPositions: [2]};
    
    const [Am, C, F, G]: Chord[] = [
      createChord(A3, chordConfigMin2ndInvDrop2),
      createChord(C3, chordConfigMaj2ndInvDrop2),
      createChord(F2, chordConfigMaj2ndInvDrop2),
      createChord(G2, chordConfigMaj2ndInvDrop2)
    ];
    
    const _ = null;
    const patternData: (Chord|null)[] = [
      Am, _, _, _,
      C,  _, C, _,
      F,  _, F, _,
      G,  G, G, G
    ];
    
    const velocity: MidiValue = 100;
    const duration: Duration = '1/4';
    const mapToStep: (chord: Chord|null) => Step = (chord: Chord|null) =>
      (null === chord) ? 
        createStep() : 
        createStep(chord.getNoteSteps(velocity, duration));
    
    const pattern: Step[] = patternData.map(mapToStep);



### Parsing chords from chord-names

This feature makes it possible to create chords from chord-names, supporting all the features of explicit configurations. 
It enables a straightforward specification of Chords by users with different levels of music-theoretical knowledge, and facilitates a more streamlined workflow even for advanced users.

**Example**

    const chordNames: string[] = [
      'A_3m7/E(drop-2)',
      'C_3/G(drop-2)',
      'F_2sus4',
      'F_2',
      'G_2sus4',
      'G_2'
    ];
    const [Am7, C, Fsus4, F, Gsus4, G]: Chord[] = chordNames.map(parseChord);
    
    const _ = null;
    const patternData: (Chord|null)[] = [
      Am7,    _, _,     _,
      C,      _, C,     _,
      Fsus4,  _, F,     _,
      G,      G, Gsus4, G
    ];
    
    const mapToStep: (chord: Chord|null) => Step = (chord: Chord|null) =>
      (null === chord) ? 
        createStep() : 
        createStep(chord.getNoteSteps());
    
    const pattern: Step[] = patternData.map(mapToStep);

**Comment by MBauerDC** [comment]
Some more comments on motivation for the changes/added features and some documentation on parsing of chord names:


## Motivation

The general motivation for beginning this project was to enable parsing of chord-names. Supporting only simple chords seemed like a job half-done - so best-case scenario would be to support every chord-quality and potential modification.

It quickly became clear that chord-names are far too complex for simple string-types structured by literal types - one would instead have to determine the individual chord-features on their own and then construct the chord from that. This led to the creation of the `ChordConfiguration`-class. 

But even with such an explicit specification, deriving the actual notes would require complex logic belonging essentially to the creation of Chords - whence a class encapsulating these methods became the preferable choice.

To generate the notes for the various chord-degrees, it would be preferable to construct them from the semitone- and octave-value of the root-note. To have those values encapsulated with a name for the note, it became convenient to represent notes themselves as a struct - and since generating new notes from those values constitutes an operation conceptually relating exclusively to the `Note`-concept and operating solely on that data, `Note`-concept became a class. It then became sensible to also make `NoteStep` into a class. (An additional motivation was the encapsulation of publicly accessible, static default-values for a few properties to facilitate streamlined construction).

Deriving chord-names from chords created from explicit specifications seemed like a nice added feature - enabling users to see the names they might use instead of an explicit specification should they so desire, and also facilitating the creation of a potential future frontend for this project.

Given the extensive type-system of typescript, maximally narrow types for arguments and values were implemented where possible.

All other changes derive from these thoughts and motivations, together with a desire to allow flexibility and expressivity in specifications and streamlining of workflows.


## Chord-name parsing documentation

A chord-name starts with a `NoteName` or a `CommonNoteName` for the root. If nothing else is specified, this will be parsed to major chord on the default octave from the `Note`-class (currently 0).
Optionally, a custom octave can be specified after the root (which can be separated from the root-note-name by an underscore). 

Next is the specification of the chord-quality (where not implied). If not specified, a major quality will be assumed unless the root-note-name (and optional octave) is followed directly by one of [7,9,11,13] indicating a dominant quality. For dominant chords, the specified extension implies the inclusion of all lower-order extensions (e.g. “C11” implies the [minor] 7 and natural 9).

Additions can be specified by “add[addition]”, where the addition-part can be any of the ones listed in the `ChordAddition` type (found, as all other types directly relating to chord-configuration, in the `ChordConfiguration`-file). Multiple additions require their own “add[addition]”-part. An exception to this rule are 6th chords and 6/9 chords. These are written e.g. “C6” and “C6/9” respectively, and are the only cases of additions not requiring an “add”-part.

Alterations are specified by a comma-separated list of values from the `ChordAlteration`-type surrounded by parentheses.
Omissions are parsed from a comma-separated list of values from the `ChordOmission`-type, prefixed by “no” and as surrounded by parentheses.

Inversions can be specified by a slash followed by the `NoteName` or `CommonNoteName` of the new lowest note at the end of the chord-name (though before potential dropped voices).

Lastly, dropped voices (counting from the highest voice) are specified by “ drop-“ followed by a dash/minus-separated list of numbers specifying the voices to be dropped, e.g. “(drop-2-4)”. 

Thus, chords can be parsed from simple names such as “E” or “Cm”, from names with specified octaves and some simple modifiers such as “D_2dim7(no5)” or “F_3add6/C”, or “A13(no7,no9)” - or from complex names such as “G_3 (#5)addb9/B (drop-2-4)” (contrived example).

As mentioned in the previous comment, proper symbols for flat, sharp and for the chord-qualities “halfDim”, “ dim”, and “Aug” can also be parsed. When generating chord-names via `writeChord`, these symbols will be used. The `GenericChord`-class will always generate a name for itself and store it in the `chordName`-property.

(Creating chords from explicit `ChordConfiguration`-instances should be largely self-documenting from the property-names and their maximally narrow literal-types.)

**Comment by MBauerDC** [comment]
I must apologize - while I was familiar with the test-command of roboter, I hadn't looked into the qa-part. Having done so now - it's a great tool (though some formatting rules seem a bit strict).

Having run the qa command myself, I will take tonight and tomorrow evening to fix the formatting, import-order etc.
I might have one or two questions about certain rules - I hope it would be okay if I ask them here should some arise.

Again - apologies for the lack of compliance.

**Comment by goloroden** [comment]
@MBauerDC Please don't worry – and it's me who has to apologize for not having replied yet.

I'm very happy and thankful for the PR, and I've taken a few times the chance to take a look at it, but I didn't have the time to walk through it all in detail.

Could you imagine splitting the PR up into a few smaller ones that are more or less independent of each other, but easier to review?

**Comment by MBauerDC** [comment]
Hi @goloroden! 

Thank you! I'm glad you find it interesting :) 
(No need to apologize - there are certainly more urgent things than reviewing a PR for non-mission-critical features on a non-mission-critical project, and I am in no rush)

I have just fixed the formatting and style errors - `npx roboter qa` now runs without encountering errors.

Splitting up the changes could certainly be done in some way - though I'm also not quite certain where / how that would be most sensible. I don't think this can be carved into really orthogonal pieces (aside from the change to `Duration`, which is trivial). 

 Because the `Note`, `NoteStep` and `Step`-code is used in every part of the song and in the `Chord`-code (which builds on top of `Notes` and `NoteSteps`), splitting between the `Note` / `NoteStep`/`Step`-changes and the `Chord`-changes would create a second PR depending deeply upon the changes from the former.

Factoring out the mere writing/printing of `Chord`s would be possible - that part is contained in the `writeChord`-file and the `chordName`-property of `Chord` with its initialization - nothing else depends upon it.

Parsing is used in the `chords`-part of the song - this and the `parseChord`-functionality be factored out into another PR (potentially together with writing/printing `Chord`s), which would leave the changes to `Note`, `NoteStep`, `Step`, their mappers and factories, and would add the functionality to create `Chord`s from explicit configurations and derive NoteSteps from them.

Still - factoring out a second PR with any of these options would make that second PR deeply dependent on the changes of the first.

If any of the above options sound good nevertheless,  please let me know - I'll do my best to split up the changes in the next days.

**Comment by goloroden** [comment]
Since we are going to do a rewrite of this module, we unfortunately won't merge this PR.

However, thanks again for your work and your contribution 😊

**Pull request closed without merging**
